config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#my_page'
  
  get 'posts/my_page' => 'posts#my_page'
  
  post '/posts/:post_id/comments/create' => 'comments#create'

  get 'comments/destroy'

  get 'comments/edit'

  get 'comments/update'
  
  get '/posts/:post_id/comments/destroy/:comment_id' => 'comments#destroy'
  
  post '/posts/:post_id/comments/update/:comment_id' => 'comments#update'
  
  get '/posts/:post_id/comments/edit/:comment_id' => 'comments#edit'
  
  post 'post/:post_id/like' => 'likes#like_toggle'
  

  devise_for :users
  resources :posts
  
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
  def has_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).nil?
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  # 사진추가
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    #avatar 추가
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar, :intro])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :intro])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new
    @comment.content = params[:content]
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id
    @comment.save
    
    redirect_to :back
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @comment.destroy
    
    redirect_to :back
  end

  def edit
    @comment = Comment.find(params[:comment_id])
    @comment.post_id = params[:post_id]
    
  end

  def update
    @comment = Comment.find(params[:comment_id])
    @comment.post_id = params[:post_id]
    @comment.content = params[:content]
    @comment.save
    
    redirect_to :back
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    
    def like_toggle
      like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
      
      if like.nil?
        Like.create(user_id:current_user.id, post_id:params[:post_id])
      else
        like.destroy
      end
      redirect_to :back 
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.reverse
  end
  
  def my_page
    @posts = Post.all
  end
  

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        @post.user_id = current_user.id
        @post.save
        format.html { redirect_to :root, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to :root, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    # respond_to do |format|
    #   format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    #   format.json { head :no_content }
  # end
    redirect_to '/posts/my_page'
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :source, :user_id)

    end
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<%=form_tag("/posts/#{@comment.post_id}/comments/update/#{@comment.id}", method: "post") do%>
<%=text_field_tag "content", nil, placeholder:"댓글", value:"#{@comment.content}"%>
<%=submit_tag "댓글수정"%>
<%end%>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" type="assets/파비콘.png" sizes="32x32" href="/파비콘.png" />

  <title>Quoty</title>
  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
    <link rel="shortcut icon" type="assets/파비콘.png" sizes="32x32" href="/파비콘.png" />

    <nav>
    <div class="nav-wrapper navbar-fixed z-depth-1">
      <a href="https://hack1-guyoung.c9users.io" class="brand-logo center"><img src="assets/logo.png"></a>
    </div>
  </nav>

<div class="fixed-action-btn">
  <a class="btn-floating btn-large #1a237e">
    <i class="large material-icons">add</i>
  </a>
  <ul>
    <li> 
      <a class="btn-floating red" href="/posts/new">
                <i class="material-icons">create</i>
              </a>
    </li>
    <li><a class="btn-floating yellow darken-1" href="/posts"><i class="material-icons">explore</i></a></li>
    <li><a class="btn-floating green" href="users/edit"><i class="material-icons">person</i></a></li>
    <li><a class="btn-floating blue" href="users/sign_out"><i class="material-icons">exit_to_app</i></a></li>
  </ul>
</div>

<script>
$(document).ready(function(){
    $('.fixed-action-btn').floatingActionButton();
  });
       
  </script>

<%= yield %>
</body><footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">멋쟁이 사자처럼 @신촌톤</h5>
                <p class="grey-text text-lighten-4">
                  이화여자대학교 박한울<br>
                  동국대학교 박현규<br>
                  연세대학교 정구영
                </p>
              </div>
              <div class="col l4 offset-l2 s12">
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2018 Copyright Quoty
            </div>
          </div>
        </footer>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>글 수정하기</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<style>
  img {
    border-radius: 50%;}
    .card-panel {
    display:inline-block;
    width:500px;
}
.btnn{
  text-decoration:none;
  background-color:white;
  border:none;
  outline:none;
}
</style>
<!--<p id="notice"><%= notice %></p>-->
<br>




    <% @posts.each do |post| %>
    <div class="row">
    <div class="col s12 m5">
      <div class="card-panel">
        <span class="black-text">
      
       
        <%= User.find(post.user).name %>
         <img src="<%= User.find(post.user).avatar.url %>" width="50" height="50" >

      

          <br>
          <blockquote>
        <%= post.content %>
        </blockquote>
        <grey-text>
        <div class="source">
        <%= post.source %>
        </div>
        </grey-text>
       
        <p>
          <%if current_user.has_like?(post)%>
            <form action = '/post/<%= post.id%>/like' method='post'>
              <button class="waves-effect waves-light btn">좋아요</button>
            </form>
          <%else%>
            <form action='/post/<%=post.id%>/like' method='post'>
              <button class="waves-effect waves-light btn">안좋아요</button>
            </form>
  
          <% end %>
          <strong>Like:</strong>
          <%= post.likes.size %>명이 좋아합니다.
        </p>
        <br>
        <% if post.user == current_user%>
        
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        
       
      <%end%>
      
      <%=form_tag("/posts/#{post.id}/comments/create", method: "post", remote: true) do%>
      <%=text_field_tag "content", nil, placeholder:"comment"%>
      <%=submit_tag "write", class:"btnn"%><br><br>
      <%= render partial: "post", object: post %>
      <%end%>
      
      <%post.comments.each do |comment|%>
      <%= User.find(comment.user_id).name %> )
      <%= comment.content%>
      <br>
      <%= link_to 'delete', "/posts/#{post.id}/comments/destroy/#{comment.id}"%>
      <%= link_to 'modify', "/posts/#{post.id}/comments/edit/#{comment.id}"%>
      <br>
      <%end%>
       
        </span>
      </div>
    </div>
  </div>
      <% end %>

    
  


<%= link_to 'New Post', new_post_path %>
<a href='/posts/my_page'>my page</a>

app/views/posts/my_page.html.erb
<style>
  .card-panel {
    display:inline-block;
    width:500px;
  }
</style>
<%if user_signed_in? %>
<%else%>
<%= link_to "login", new_user_session_path %>
<%= link_to "join", new_user_registration_path %>
<%end%>
<div class="info">
    <div class="profile">
      <div class="profile-image">
        <!---이따 프로필 주소로 바꾸기---->
        <img src="<%= current_user.avatar.url %>" alt="profile" width="140px" height="140px" class="circle z-depth-4">
      </div>
      <div class="name">
        <h6><%= current_user.name %></h6>
      </div>
      <div class="status">
        <p><%= current_user.intro %></p>
      </div>
    </div>
  </div>
  
  
      <div class="col s4"></div>
      <div class="col s4">
        
        <% @posts.each do |post| %>
        <% if post.user == current_user%>
        <div class="my-posts">
      <div class="card-panel">
        <div class="more">
          <!-- Dropdown Trigger -->
          <a class='dropdown-trigger' href='#' data-target='dropdown1'><i class="material-icons">more_vert</i></a>
        
          <!-- Dropdown Structure -->
          <ul id='dropdown1' class='dropdown-content'>
            <li>
                <%= link_to '수정', edit_post_path(post) %>
            </li>
            <li class="divider" tabindex="-1"></li>
            <li><%= link_to '삭제', post, method: :delete, data: { confirm: '정말요?' } %></li>
          </ul>
        </div>
        <%end%>
        <% if post.user == current_user%>
        <blockquote>
          <span class="black-text">
          <%= post.content %>
          <hr>
        </blockquote>
        <div class="source">
          <span class="grey-text">
          <%= post.source %>
          </span>
          </div>
          <%end%>
          
          
        <div class="card-action">
            </div>
          </div>
        </div>
    
      <% end %>
      </div>
        </div>
        
      </div>
      <div class="col s4"></div>
      
      
      
   
    
<script>
 $('.dropdown-trigger').dropdown();
  
   $(document).ready(function(){
    $('.modal').modal();
  });
</script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>